resolution_3d: 0.02  # point cloud resolution (mean point-to-point distance).
distances_near_thr_factor: 1.5   # points with distances less than the specified value will be
                                 # selected as sharp (in units of resolution_3d).
knn_radius_factor: 3.0    # max distance to connect a pair of points
                          # in knn graph (in units of resolution_3d).
min_cc_points_to_keep: 30   # min number of points in connected component to get
                            # through the filtering (set to -1 to skip filtering)
subsample_rate: 0   # if this is specified and is greater than 0,
                    # subsample the input point cloud by keeping
                    # at most ceil(n_points * subsample_rate) points