[package]
name = "patch_generation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embree = "0.3.8"
cgmath = "0.18.0"
image = "0.24.4"
obj-rs = "0.6"
tobj = "3.2.3"
